#4 플레이스토어 업데이트 준비
teamtuna/OpenWeather pull request #8
Opened 2019-11-09 02:48 UTC by karrel84

사용불가한 api 호출 제거
udpate gradle version

2019-11-09 06:14 UTC, eastar-dev submitted a review, later dismissed

2019-11-11 09:57 UTC, babosamo commented on app/src/test/java/com/karrel/openweather/network/WeatherRetrofitTest.kt
> +        println("error body : ${response.message()}")
```suggestion
if (response.code() == 200) {
            println("data : $data")
        } else {
             println("error body : ${response.message()}")      
        }
```

2019-11-11 09:58 UTC, babosamo requested changes
성공, 실패에 대한 구분 없이 로그를 찍고 있습니다.

2019-11-11 09:58 UTC, babosamo commented on app/src/test/java/com/karrel/openweather/network/WeatherRetrofitTest.kt
> +        println("error body : ${response.message()}")
이런 형태로 로그를 찍는건 어떨까요?

2019-11-11 14:48 UTC, pennya approved these changes

2019-11-14 14:16 UTC, karrel84 commented on app/src/test/java/com/karrel/openweather/network/WeatherRetrofitTest.kt
> +        println("error body : ${response.message()}")
@babo

2019-11-15 01:27 UTC, babosamo approved these changes
👍

2019-11-15 01:27 UTC, merged